### ISSUE TITLE
I can add add project but can't delete it, and can add build but can't delet build

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#1]
![issue](https://github.com/mylonics/zephyr-ide/assets/169084509/75cb6c0d-db5c-42f9-b481-dd47dea3a72f)

I can add add project but can't delete it, and can add build but can't delet build!

**Comment by rijesha** [comment]
Thanks for the issue. 
It may be that the GUI is not actually updating. 
Could you try "Zephyr IDE:  Load Projects from File" Command?

**Comment by rijesha** [comment]
or restarting VS code and seeing if it deletes correctly?

**Comment by IOT4566** [comment]
> Thanks for the issue. 谢谢你的问题。 It may be that the GUI is not actually updating.可能是 GUI 实际上没有更新。 Could you try "Zephyr IDE: Load Projects from File" Command?您可以尝试“Zephyr IDE：从文件加载项目”命令吗？

Yes, this issue is caused by the GUI not being updated, as closing vscode and reopening it reveals that it can be deleted. so, you can call the api of update the GUI after handling the deletion to solve this problem, thank you!

**Comment by IOT4566** [comment]
> Thanks for the issue.. It may be that the GUI is not actually updating. Could you try "Zephyr IDE: Load Projects from File" Command?

NO, this issue is not caused by the GUI not being updated, beacause i click buttom for delete project or bulid then closing vscode and reopening it, but  it can not be deleted

**Comment by rijesha** [comment]
I have pushed an update. The update should be available on the marketplace in 5 minutes or so.

**Comment by IOT4566** [comment]
> I have pushed an update. The update should be available on the marketplace in 5 minutes or so.

OK，I try it a few, thanks!

**Comment by IOT4566** [comment]
> I have pushed an update. The update should be available on the marketplace in 5 minutes or so.

I have updated and restart vscode, but the issues still  persists！

**Comment by rijesha** [comment]
Ok, so the extension is on 1.0.7?
Could you send me .vscode/settings.json file?

**Comment by IOT4566** [comment]
> Ok, so the extension is on 1.0.7? Could you send me .vscode/settings.json file?

![1 07](https://github.com/mylonics/zephyr-ide/assets/169084509/3cccf5d1-6d9e-40a3-abf8-d88802b15111)
[settings.json](https://github.com/mylonics/zephyr-ide/files/15225278/settings.json)

**Comment by rijesha** [comment]
Could you put this in your settings.json file and see if the issue is still there?
"zephyr-ide.use-zephyr-ide-json": false,

**Comment by rijesha** [comment]
![image](https://github.com/mylonics/zephyr-ide/assets/7819200/c016f0d6-967f-4857-8af1-d90da566eb3d)

When you press delete do you see the popup appear asking you if you are sure?

**Comment by IOT4566** [comment]
> Could you put this in your settings.json file and see if the issue is still there? "zephyr-ide.use-zephyr-ide-json": false,

![001](https://github.com/mylonics/zephyr-ide/assets/169084509/4e9b4135-dff8-4196-b075-e091b22aa345)

I put "zephyr-ide.use-zephyr-ide-json": false,, but the issue is still there. when i press delete i can not see the popup appear  asking me  if you are sure

**Comment by IOT4566** [comment]
> ![image](https://private-user-images.githubusercontent.com/7819200/328292758-c016f0d6-967f-4857-8af1-d90da566eb3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjM1MzgsIm5iZiI6MTcxNTAyMzIzOCwicGF0aCI6Ii83ODE5MjAwLzMyODI5Mjc1OC1jMDE2ZjBkNi05NjdmLTQ4NTctOGFmMS1kOTBkYTU2NmViM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTkyMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRlZWYxNjlhY2E1ZDkzNzgyMDM2YzEyYjZlNTgxYWFhYjkwZjIwMTE0ZjMzNGVkNzBlMDQwZTc4YzdkYzY5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sdlyK0rzGhYmEIfFf1x26cZ8El0YgOB6NlQ1QIWSfgk)
> 
> When you press delete do you see the popup appear asking you if you are sure?


https://github.com/mylonics/zephyr-ide/assets/169084509/53d380b5-5754-4b70-962f-8a421bea11fe

**Comment by rijesha** [comment]
Could you "Zephyr IDE: Clear Project" and try readding projects.
Or start fresh from a new folder.

**Comment by IOT4566** [comment]
> Could you "Zephyr IDE: Clear Project" and try readding projects. Or start fresh from a new folder.


https://github.com/mylonics/zephyr-ide/assets/169084509/48ecebb4-f4ed-4592-9bd8-218621db284c

do you mean by this?

**Comment by rijesha** [comment]
Yes. It is interesting that the button is not doing anything. 
It seems like none of the buttons on the GUI are working. Can you add a new build from the GUI or did you add it from the command pallet?

**Comment by rijesha** [comment]
can you also share a zip of the folder. (you can leave out the external directory though)

**Comment by IOT4566** [comment]
> Yes. It is interesting that the button is not doing anything.是的。有趣的是，该按钮没有执行任何操作。 It seems like none of the buttons on the GUI are working. Can you add a new build from the GUI or can you only add them from the command pallet?GUI 上的所有按钮似乎都不起作用。您可以从 GUI 添加新版本，还是只能从命令托盘添加它们？



> Yes. It is interesting that the button is not doing anything. It seems like none of the buttons on the GUI are working. Can you add a new build from the GUI or can you only add them from the command pallet?

I add a new build from gui

**Comment by IOT4566** [comment]
> Yes. It is interesting that the button is not doing anything. It seems like none of the buttons on the GUI are working. Can you add a new build from the GUI or can you only add them from the command pallet?

I add a new build from the gui

**Comment by rijesha** [comment]
Ok. Could you open the extension host logs and let me know what happens when you try deleting a build?
Ctrl-Shift-p -> Show Logs -> Extension Host

**Comment by rijesha** [comment]
Oh your notifications are just off. 
![image](https://github.com/mylonics/zephyr-ide/assets/7819200/9d1ea843-0559-4bd8-9d08-ea03bb66657f)

It should look like this. Or click on the bell icon to see a notification.
![image](https://github.com/mylonics/zephyr-ide/assets/7819200/cd6b3269-b997-4770-a89a-d6099088fd2a)

**Comment by IOT4566** [comment]
> can you also share a zip of the folder. (you can leave out the external directory though)

ok, but i no how send a zip file

**Comment by IOT4566** [comment]
> Oh your notifications are just off. ![image](https://private-user-images.githubusercontent.com/7819200/328304767-9d1ea843-0559-4bd8-9d08-ea03bb66657f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjY0NjQsIm5iZiI6MTcxNTAyNjE2NCwicGF0aCI6Ii83ODE5MjAwLzMyODMwNDc2Ny05ZDFlYTg0My0wNTU5LTRiZDgtOWQwOC1lYTAzYmI2NjY1N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMjAwOTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE3N2RmNGZhMThiYTQ4ZmE5NmNiODAzNGVhM2EyNWE4MTMwNDQ1NTM2YTI3MWI1Nzc0MjAwNDljYTcyZjJkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nfDB9zWwFodJHTqNj3CSHmXTv9xNQovbpU3e2Nhjsk4)
> 
> It should look like this. Or click on the bell icon to see a notification. ![image](https://private-user-images.githubusercontent.com/7819200/328304625-cd6b3269-b997-4770-a89a-d6099088fd2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjY0NjQsIm5iZiI6MTcxNTAyNjE2NCwicGF0aCI6Ii83ODE5MjAwLzMyODMwNDYyNS1jZDZiMzI2OS1iOTk3LTQ3NzAtYTg5YS1kNjA5OTA4OGZkMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMjAwOTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWY4M2QxYjAzMTRhYTk0Yzk4Njc1OGQ1NDM1ZjU5Y2ZkMDAwNDY0YWI5ZTg3ZTQ3NzkyZWUyMTJlYTAxZDI1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mHG0fnQtkmSG8P59Jab44ZNiwrs9V2WAPyQi9kT3uyc)

oh, yes, it's this caused, it's ok now, thank you very much!
Additionally, when adding a project from a template, can we add a fold path that allows users to specify the project

**Comment by rijesha** [comment]
> oh, yes, it's this caused, it's ok now, thank you very much! Additionally, when adding a project from a template, can we add a fold path that allows users to specify the project

Do you mean the ability to manually browse to a desired sample project?
Or do you mean renaming the project folder after it is copied?  (Project blinky is added as project blinky2)
Or do you mean putting the project into a subfolder?  (Project blinky is added as project subfolder/blinky)

**Comment by IOT4566** [comment]
> > oh, yes, it's this caused, it's ok now, thank you very much! Additionally, when adding a project from a template, can we add a fold path that allows users to specify the project
> 
> Do you mean the ability to manually browse to a desired sample project? Or do you mean renaming the project folder after it is copied? (Project blinky is added as project blinky2) Or do you mean putting the project into a subfolder? (Project blinky is added as project subfolder/blinky)

yes i mean putting the project into a subfolder? (Project blinky is added as project subfolder/blinky), the subfolder can be brow by user and the project folder can be rename also

**Comment by rijesha** [comment]
Yea that is something I could do. Please make a new issue for it, and I will get to it when I have a chance. To rename the project, the CMakeLists file needs to be parsed and the project like needs to be updated, so that adds a little bit of complexity.
